force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team__c/Project_Team__c.object-meta.xml
<CustomObject>
    <description>This is child to Project where users can select a User and can assign a Role as well</description>
    <label>Project Team</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Project Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>check the checkbox if selected user is primary.</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Team__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Lookup to Project to select Project</description>
    <inlineHelpText>Select Project Name Here</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/Project_Team_Primary.cls
/*******************************************
*Class name :Project_Team_Primary
*Description : This class contains the logic to maintain only One Primary user at a time on Project_Team__c at Project ( Projec_Role__c level ) 
*and being called from Process Builder.
*Date :
*Developer Name : Vineet Kumar
********************************************/
public class Project_Team_Primary {
    
    // this method will update Project Team records, will be called from process builder
    @InvocableMethod
    Public static void updatePrimaryProjectTeamMember(List<Project_Team__c>  ptRecords)
    {
        Set<Id> projectIds = new Set<Id>();   // add project ids
        Set<Id> teamIds = new Set<Id>();      // add project team record ids
        
        for(Project_Team__c pt:ptRecords)
        {
            projectIds.add(pt.Project__c);
            teamIds.add(pt.id);
        }
        
        List<Project_Team__c> ptList=new List<Project_Team__c>();
        for(Project_Team__c pt:[SELECT Id,Primary__c FROM Project_Team__c WHERE Project__c IN :projectIds AND id NOT IN : teamIds AND Primary__c=TRUE ])
        {
            pt.Primary__c=false;
            ptList.add(pt);
        }
        if(!ptList.isEmpty())
        {
            update ptList;
        }
    }
    
}