force-app/main/default/objects/Vendor_Enquiry__c/Vendor_Enquiry__c.object-meta.xml
<CustomObject>
    <label>Vendor Enquiry</label>
    <nameField>
        <label>Vendor Enquiry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor_Enquiry</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Enquiry__c/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <inlineHelpText>Please provide a valid contact number.</inlineHelpText>
    <label>Contact number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Vendor_Enquiry__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <inlineHelpText>Please provide Country name.</inlineHelpText>
    <label>Country</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor_Enquiry__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <inlineHelpText>Please provide your role at organisation.</inlineHelpText>
    <label>Designation</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor_Enquiry__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <inlineHelpText>Please enter your first name</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor_Enquiry__c/fields/How_did_you_hear_about_TIG__c.field-meta.xml
<CustomField>
    <fullName>How_did_you_hear_about_TIG__c</fullName>
    <inlineHelpText>Which source is helped you to get to know about this.</inlineHelpText>
    <label>How did you hear about TIG?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor_Enquiry__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <inlineHelpText>Please enter your lastname</inlineHelpText>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor_Enquiry__c/fields/Name_of_the_Organization__c.field-meta.xml
<CustomField>
    <fullName>Name_of_the_Organization__c</fullName>
    <inlineHelpText>Please provide Company/Organization name.</inlineHelpText>
    <label>Name of the Organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor_Enquiry__c/fields/Official_Email_id__c.field-meta.xml
<CustomField>
    <fullName>Official_Email_id__c</fullName>
    <inlineHelpText>Please provide a valid mail address.</inlineHelpText>
    <label>Official Email id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Vendor_Enquiry__c/fields/Query__c.field-meta.xml
<CustomField>
    <fullName>Query__c</fullName>
    <inlineHelpText>please post your query here.</inlineHelpText>
    <label>Query</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor_Enquiry__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Reference</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WebtoVendorEnquiry.cls
/*******************
 * Class Name
 * Description: It's a Rest Web Service. which is used to create vendor inqueries into system coming from web.
 * 
 * 
 * ********************/


@RestResource(urlMapping='/VendorEnquiry/*')
global class WebtoVendorEnquiry {

    /*public VendorEnquiry_WebtoLeadClass() {

    }*/
   @HttpPost
    global static responseWrapper VendorEnquiryCreation(){
        RestRequest req = RestContext.request; //the RestRequest for the Apex REST method
        responseWrapper responseJSON = new responseWrapper();
        Map<String, Object> body = new Map<String, Object>();
        List<Vendor_Enquiry__c> LstvEnq = new List<Vendor_Enquiry__c>();
        String jsonBody = req.requestBody.toString();
        if (!String.isBlank(jsonBody)) { 
			body = (Map<String, Object>)JSON.deserializeUntyped(jsonBody); //deserializes the JSON string into collections of primitive data types
            system.debug('body========>'+body.get(responseJSON.contactNumber));
            Vendor_Enquiry__c vEnq = new Vendor_Enquiry__c();
            vEnq.Contact_number__c = String.valueof(body.get(responseJSON.contactNumber));
            vEnq.First_Name__c = String.valueof(body.get(responseJSON.firstName));
            vEnq.Last_Name__c = String.valueof(body.get(responseJSON.lastName));
            vEnq.Official_Email_id__c = String.valueof(body.get(responseJSON.officialEmailId));
            vEnq.Name_of_the_Organization__c = String.valueof(body.get(responseJSON.nameOfTheOrganisation));
            vEnq.How_did_you_hear_about_TIG__c = String.valueof(body.get(responseJSON.howDidYouHearAboutTIG));
            vEnq.Query__c = String.valueof(body.get(responseJSON.query));
            vEnq.Designation__c = String.valueof(body.get(responseJSON.designation));
            vEnq.Country__c = String.valueof(body.get(responseJSON.country));
            vEnq.Source__c='Web';
                LstvEnq.add(vEnq);
        }   
        if(LstvEnq.size() > 0){
            insert LstvEnq; // inserting vendor enquiries  into database
        }
        return responseJSON;
    }
    global class responseWrapper{

        global string contactNumber {get;set;}
        global string firstName {get;set;}
        global string lastName {get;set;}
        global string officialEmailId {get;set;}
        global string nameOfTheOrganisation {get;set;}
        global string howDidYouHearAboutTIG {get;set;}
        global string query {get;set;}
        global string designation {get;set;}
        global string country {get;set;}
        global string source {get;set;}
        
        //constructor
		global responseWrapper() {
			//default all values
			this.contactNumber = 'contactNumber';
			this.firstName = 'firstName';
			this.lastName = 'lastName';
            this.officialEmailId='officialEmailId';
            this.nameOfTheOrganisation='nameOfTheOrganisation';
            this.howDidYouHearAboutTIG='howDidYouHearAboutTIG';
            this.query='query';
            this.designation='designation';
            this.country='country';
            this.source='source';
			
        }
    }  
}