force-app/main/default/objects/Vendor_Enquiry__c/Vendor_Enquiry__c.object-meta.xml
<CustomObject>
    <label>Vendor Enquiry</label>
    <nameField>
        <label>Vendor Enquiry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor_Enquiry</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Enquiry__c/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <inlineHelpText>Please provide a valid contact number.</inlineHelpText>
    <label>Contact number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Vendor_Enquiry__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <inlineHelpText>Please enter your first name</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor_Enquiry__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <inlineHelpText>Please enter your lastname</inlineHelpText>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VendorEnquiry_WebtoLeadClass.cls
@RestResource(urlMapping='/Enquiry/*')
global class VendorEnquiry_WebtoLeadClass {

    /*public VendorEnquiry_WebtoLeadClass() {

    }*/
    @HttpPost
    global static responseWrapper VendorEnquiryCreation(){
        RestRequest req = RestContext.request; //the RestRequest for the Apex REST method
        responseWrapper responseJSON = new responseWrapper();
        Map<String, Object> body = new Map<String, Object>();
        List<Vendor_Enquiry__c> LstvEnq = new List<Vendor_Enquiry__c>();
        String jsonBody = req.requestBody.toString();
        if (!String.isBlank(jsonBody)) { 
			body = (Map<String, Object>)JSON.deserializeUntyped(jsonBody); //deserializes the JSON string into collections of primitive data types
            system.debug('body========>'+body.get(responseJSON.contactNumber));
            Vendor_Enquiry__c vEnq = new Vendor_Enquiry__c();
            vEnq.Contact_number__c = String.valueof(body.get(responseJSON.contactNumber));
            vEnq.First_Name__c = String.valueof(body.get(responseJSON.firstName));
            vEnq.Last_Name__c = String.valueof(body.get(responseJSON.lastName));
            LstvEnq.add(vEnq);
        }   
        if(LstvEnq.size() > 0){
            insert LstvEnq;
        }
        return responseJSON;
    }
    global class responseWrapper{

        global string contactNumber {get;set;}
        global string firstName {get;set;}
        global string lastName {get;set;}
        
        //constructor
		global responseWrapper() {
			//default all values
			this.contactNumber = 'contactNumber';
			this.firstName = 'firstName';
			this.lastName = 'lastName';
			
        }
    }
}