force-app/main/default/objects/Due_Diligence__c/Due_Diligence__c.object-meta.xml
<CustomObject>
    <label>Due Diligence</label>
    <nameField>
        <displayFormat>DD-{0000}</displayFormat>
        <label>Due Diligency Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Due Diligences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Due_Diligence__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Due Diligences</relationshipLabel>
    <relationshipName>Due_Diligences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Due_Diligence__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DueDiligenceTriggerHandler.cls
public class DueDiligenceTriggerHandler {
    public static void updatecheckBox(List<Due_Diligence__c> dueDiligenceList){
        Set<ID> partnerId=new set<ID>(); // Set to save the id for partners
        for(Due_Diligence__c due:dueDiligenceList){
            partnerId.add(due.Partner__c);
        }
        List<Due_Diligence__c> dueDiligenceList2=[Select id,Status__c,Active__c,Partner__c from Due_Diligence__c where Partner__c In:partnerId];
        List<Due_Diligence__c> updateddueDiligenceList=new List<Due_Diligence__c>();
        for(Due_Diligence__c due:dueDiligenceList2){
            due.Status__c='Completed';
            due.Active__c=False;
            updateddueDiligenceList.add(due);
        }
        if(!updateddueDiligenceList.isempty()){
            update updateddueDiligenceList;
        } 
        
        
    }
    
}