force-app/main/default/objects/ContentVersion/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObjectType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NDA</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>SOW</fullName>
            </value>
            <value>
                <fullName>Change Note</fullName>
            </value>
            <value>
                <fullName>Billing Sheet</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>MOM</fullName>
            </value>
            <value>
                <fullName>Vendor Capability</fullName>
            </value>
            <value>
                <fullName>Partner Presence</fullName>
            </value>
            <value>
                <fullName>Financial Information</fullName>
            </value>
            <value>
                <fullName>Escalation Matrix</fullName>
            </value>
            <value>
                <fullName>Purchase Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Invoice__c</fullName>
            </value>
            <value>
                <fullName>Project__c</fullName>
            </value>
            <value>
                <fullName>Billing_Information__c</fullName>
            </value>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< DEV
            <value>
                <fullName>Vendor_Enquiry__c</fullName>
                <label>Vendor Enquiry</label>
            </value>
========================================================================
            <value>
                <fullName>Order__c</fullName>
            </value>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> feature/VendorPO
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Custom Order Object</description>
    <label>TIG Order</label>
    <nameField>
        <label>PO Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PurchaseOrderPDFControllerSaveDownload.cls
public class PurchaseOrderPDFControllerSaveDownload{
    
    
    public PurchaseOrderPDFControllerSaveDownload(ApexPages.StandardController controller){
        // saveFile();
    }
    public PurchaseOrderPDFControllerSaveDownload(){
        // saveFile();
    }
    
    
    
    public void saveFile(){
        id ids = apexpages.currentpage().getparameters().get('id');
        system.debug('id :'+ids);
        
        PageReference ref = new PageReference('/apex/PurchaseOrderPDFGenerator?id=' + ids);
        String PONumber=[SELECT Name FROM Order__c where id=:ids].Name;
        String pdfName='Purchase Order-'+PONumber;
        List<ContentVersion> listversion = [select contentDocumentId, contentDocument.title from ContentVersion where ContentDocument.title = :pdfName];                                     
        System.debug('listversion : ' + listversion);
        ContentVersion fl = new ContentVersion();
        fl.ContentLocation = 'S';
        fl.PathOnClient = 'file.pdf';
        fl.Origin = 'H';
        fl.Title = 'Purchase Order-'+PONumber;
        fl.SObjectType__c='Order__c';
        fl.Document_Type__c='Purchase Order';
        if(Test.isRunningTest()) { 
            
            fl.VersionData = blob.valueOf('Unit.Test');
        }else{
            fl.VersionData = ref.getContentAsPdf();
        }
        if (!listversion.isEmpty()){
            fl.ContentDocumentId= listversion[0].ContentDocumentId;
        }
        Savepoint sp = Database.setSavepoint();
        try{
            insert fl;
            if(listversion.isEmpty()){
                
                fl = [select ContentDocumentId from ContentVersion where id =: fl.Id];
                ContentDocumentLink cl = new ContentDocumentLink(
                    LinkedEntityId = ids,
                    ContentDocumentId = fl.ContentDocumentId,
                    ShareType = 'I'
                );
                insert cl;   
            }         
        } catch(Exception e) {
            Database.rollback(sp);
            System.debug(e.getMessage());          
            throw e;
        }
        
    }    
}