force-app/main/default/objects/ContentVersion/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObjectType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NDA</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>SOW</fullName>
            </value>
            <value>
                <fullName>Change Note</fullName>
            </value>
            <value>
                <fullName>Billing Sheet</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>MOM</fullName>
            </value>
            <value>
                <fullName>Vendor Capability</fullName>
            </value>
            <value>
                <fullName>Partner Presence</fullName>
            </value>
            <value>
                <fullName>Financial Information</fullName>
            </value>
            <value>
                <fullName>Escalation Matrix</fullName>
            </value>
            <value>
                <fullName>Purchase Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Invoice__c</fullName>
            </value>
            <value>
                <fullName>Project__c</fullName>
            </value>
            <value>
                <fullName>Billing_Information__c</fullName>
            </value>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< DEV
            <value>
                <fullName>Vendor_Enquiry__c</fullName>
                <label>Vendor Enquiry</label>
            </value>
========================================================================
            <value>
                <fullName>Order__c</fullName>
            </value>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> feature/VendorPO
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FileOrganiserHandler.cls
public with sharing class FileOrganiserHandler {
    
    @AuraEnabled(cacheable=true)
    public static List<FileWrap> getFiles(Id recordId){
        
        List<FileWrap> filesLst = new List<FileWrap>();

        for(ContentDocumentLink cDL: [SELECT Id, ContentDocumentId, ContentDocument.Title, ContentDocument.ContentModifiedDate, 
                                        ContentDocument.LatestPublishedVersion.Document_Type__c, ContentDocument.LatestPublishedVersionId,
                                        ContentDocument.LatestPublishedVersion.ContentModifiedBy.Name
                                        FROM ContentDocumentLink WHERE LinkedEntityId =: recordId]){
            
            FileWrap fWrap = new FileWrap();

            fWrap.id = cDL.ContentDocumentId;
            fWrap.title = cDL.ContentDocument.Title;
            fWrap.documentType = cDL.ContentDocument.LatestPublishedVersion.Document_Type__c;
            fWrap.uploadedBy = cDL.ContentDocument.LatestPublishedVersion.ContentModifiedBy.Name;
            fWrap.uploadedDate = cDL.ContentDocument.ContentModifiedDate;
            
            filesLst.add(fWrap);
        }

        return filesLst;                    
    }

    @AuraEnabled
    public static void updateFile(Id recordId, String objType, String documentType){
        
        ContentVersion file = [SELECT Id, Title, SObjectType__c, Document_Type__c 
                                FROM ContentVersion 
                                WHERE ContentDocumentId =: recordId
                                AND IsLatest = true];

        file.SObjectType__c = objType;
        file.Document_Type__c = documentType;

        update file;
    }

    public class FileWrap{

        @AuraEnabled
        public String id;

        @AuraEnabled
        public String title;

        @AuraEnabled
        public String documentType;

        @AuraEnabled
        public Datetime uploadedDate;

        @AuraEnabled
        public String uploadedBy;
    }
}