force-app/main/default/objects/Billing_Information__c/Billing_Information__c.object-meta.xml
<CustomObject>
    <description>This will hold billing related information for a project.</description>
    <label>Billing Information</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Information</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Information__c/fields/Billing_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_End_Date__c</fullName>
    <label>Billing End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing_Information__c/fields/Billing_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Start_Date__c</fullName>
    <label>Billing Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing_Information__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Billing Information</relationshipLabel>
    <relationshipName>Billing_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Half-Yearly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>ADHOC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Last_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Billing_Date__c</fullName>
    <description>Used internally in trigger</description>
    <label>Last Billing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <label>Payment Terms</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NET10</fullName>
            </value>
            <value>
                <fullName>NET30</fullName>
            </value>
            <value>
                <fullName>NET45</fullName>
            </value>
            <value>
                <fullName>NET60</fullName>
            </value>
            <value>
                <fullName>NET90</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_End_Date__c</fullName>
    <label>Project End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_IT_Billing_Entity__c.field-meta.xml
<CustomField>
    <fullName>Total_IT_Billing_Entity__c</fullName>
    <label>Total IT Billing Entity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Total IT Consult LLP</fullName>
            </value>
            <value>
                <fullName>Total IT Consult Pty ltd</fullName>
            </value>
            <value>
                <fullName>TIC Netherlands B.V.</fullName>
            </value>
            <value>
                <fullName>Total IT Global UK Limited</fullName>
            </value>
            <value>
                <fullName>Total IT Global Sdn Bhd</fullName>
            </value>
            <value>
                <fullName>Total IT Consult Pte Ltd</fullName>
            </value>
            <value>
                <fullName>Total IT Global Pte Ltd</fullName>
            </value>
            <value>
                <fullName>Total IT Global NZ Ltd</fullName>
            </value>
            <value>
                <fullName>Total IT Global HK Ltd</fullName>
            </value>
            <value>
                <fullName>Total IT Global KK,Japan</fullName>
            </value>
            <value>
                <fullName>TIGM Global Computer Systems Services</fullName>
            </value>
            <value>
                <fullName>Total IT Global Inc.</fullName>
            </value>
            <value>
                <fullName>Total IT Consult DK ApS</fullName>
            </value>
            <value>
                <fullName>Total IT Global Finland OY</fullName>
            </value>
            <value>
                <fullName>TOTAL IT GLOBAL POLAND Sp. z o .o</fullName>
            </value>
            <value>
                <fullName>Total IT Global France</fullName>
            </value>
            <value>
                <fullName>Total IT Global Company Limited</fullName>
            </value>
            <value>
                <fullName>Total IT Germany GMBH</fullName>
            </value>
            <value>
                <fullName>Total IT Norway AS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Team__c/Project_Team__c.object-meta.xml
<CustomObject>
    <description>This is child to Project where users can select a User and can assign a Role as well</description>
    <label>Project Team</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Project Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>check the checkbox if selected user is primary.</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Team__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Lookup to Project to select Project</description>
    <inlineHelpText>Select Project Name Here</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project_Team__c/fields/Project_Role__c.field-meta.xml
<CustomField>
    <fullName>Project_Role__c</fullName>
    <inlineHelpText>Select the role of this user.</inlineHelpText>
    <label>Project Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project Executive</fullName>
            </value>
            <value>
                <fullName>Service Desk Agent</fullName>
            </value>
            <value>
                <fullName>Sr. Project Executive</fullName>
            </value>
            <value>
                <fullName>Service Delivery Executive</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>SDM</fullName>
            </value>
            <value>
                <fullName>Project Management Head</fullName>
            </value>
            <value>
                <fullName>Regional Head Service Delivery</fullName>
            </value>
            <value>
                <fullName>Global delivery Director</fullName>
            </value>
            <value>
                <fullName>Global OPS Head</fullName>
            </value>
            <value>
                <fullName>Resource may have Engineers(Contractor-Dispatch, Contractor-FTE, FTE)</fullName>
            </value>
            <value>
                <fullName>Service Desk Lead</fullName>
            </value>
            <value>
                <fullName>Service Desk Manager</fullName>
            </value>
            <value>
                <fullName>Service Delivery Manager</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Account Director</fullName>
            </value>
            <value>
                <fullName>Client SDM</fullName>
            </value>
            <value>
                <fullName>TIG SDM</fullName>
            </value>
            <value>
                <fullName>RDH</fullName>
            </value>
            <value>
                <fullName>Sales Executive</fullName>
            </value>
            <value>
                <fullName>Pre-Sales Team</fullName>
            </value>
            <value>
                <fullName>Sales Team</fullName>
            </value>
            <value>
                <fullName>AR Execuive</fullName>
            </value>
            <value>
                <fullName>AR Sr. Executive</fullName>
            </value>
            <value>
                <fullName>AR Manager</fullName>
            </value>
            <value>
                <fullName>AR Head</fullName>
            </value>
            <value>
                <fullName>AP Executive</fullName>
            </value>
            <value>
                <fullName>AP Sr. Executive</fullName>
            </value>
            <value>
                <fullName>AP Manager</fullName>
            </value>
            <value>
                <fullName>AP Head</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Team__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_Data_Factory.cls
/******************************************************
*Class Name: Test_Data_Factory
*Description : will hold test data that will be used in test classes
*Date:  Sep 2020
*Developer Name: Vineet Kumar
******************************************************/
@isTest
public class Test_Data_Factory {
    
    public static Account createAccount(String recordTypeName)
    {
        Account acc=new Account();
        acc.Name='TaTa';
        acc.Type='Partner';
        acc.RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
        return acc;      
    }
    
    public static Contact createContact()
    {
        Contact con=new Contact();
        con.firstName='Albert';
        con.LastName='K';
        con.Email='albert@manras.com'; 
        return con;
    }
    
    public static Project__c createProject(String billingFrequency)
    {
        List<Project__c> projList=new List<Project__c>();
        Project__c proj=new Project__c();
        proj.Name='SFDC Impl';
        proj.Project_Start_Date__c=Date.today();
        proj.Project_End_Date__c=Date.today()+5;
        proj.Payment_Term__c='NET10';
        proj.Total_IT_Billing_Entity__c='Total It Consult LLP';
        proj.Billing_Frequency__c=billingFrequency;
      //  proj.Last_Billing_Date__c=Date.today()-1;
        return proj;
    }
    
    public static Project_Team__c createProjectTeam(String recordTypeName, Boolean primary)
    {
        Project_Team__c pt=new Project_Team__c();
        pt.Project_Role__c='SDM';
        pt.User__c=UserInfo.getUserId();
        pt.Primary__c=primary;
        pt.RecordTypeId=Schema.SObjectType.Project_Team__c.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
        return pt;
        
    }
    
    public static Billing_Information__c createBillingInformation()
    {
        Billing_Information__c bi=new Billing_Information__c();
        bi.Billing_Start_Date__c=System.today();
        bi.Billing_End_Date__c=System.today()+5;
        return bi;
        
    }
    
    
}