force-app/main/default/objects/Billing_Information__c/Billing_Information__c.object-meta.xml
<CustomObject>
    <description>This will hold billing related information for a project.</description>
    <label>Billing Information</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Information</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Information__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This field is used to identify that It&apos;s Vendor/Customer.</description>
    <formula>Project__r.Customer__r.RecordType.DeveloperName</formula>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Information__c/fields/Approval_Comment_Check__c.field-meta.xml
<CustomField>
    <fullName>Approval_Comment_Check__c</fullName>
    <description>used in Billing approval for making comment required on rejection</description>
    <label>Approval Comment Check</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Required</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Information__c/fields/Approved_by_AR_Manager__c.field-meta.xml
<CustomField>
    <fullName>Approved_by_AR_Manager__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used internally in Billing Approval Process</description>
    <label>Approved by AR Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Information__c/fields/Billing_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Billing_Approval_Status__c</fullName>
    <description>will hold status of the approval</description>
    <label>Billing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upload Raw  Data</fullName>
                <default>true</default>
                <label>Upload Raw  Data</label>
            </value>
            <value>
                <fullName>Sent to SDM</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
            <value>
                <fullName>Sent to AR Executive/ AR Sr. Executive</fullName>
            </value>
            <value>
                <fullName>Sent to AR Manager</fullName>
            </value>
            <value>
                <fullName>Sent to AR Head</fullName>
            </value>
            <value>
                <fullName>Sent to Client SDM</fullName>
            </value>
            <value>
                <fullName>Sent to TIG SDM</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Billing Approved</fullName>
            </value>
            <value>
                <fullName>Rejected by AR Executive/ AR Sr. Executive</fullName>
                <isActive>false</isActive>
                <label>Rejected by AR Executive/ AR Sr. Executive</label>
            </value>
            <value>
                <fullName>Rejected by AR Head</fullName>
                <isActive>false</isActive>
                <label>Rejected by AR Head</label>
            </value>
            <value>
                <fullName>Rejected by AR Manager</fullName>
                <isActive>false</isActive>
                <label>Rejected by AR Manager</label>
            </value>
            <value>
                <fullName>Rejected by Client SDM</fullName>
                <isActive>false</isActive>
                <label>Rejected by Client SDM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Information__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Billing Information</relationshipLabel>
    <relationshipName>Billing_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Information__c/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Billing_Information__c/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Project__c/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/Project_Team__c/Project_Team__c.object-meta.xml
<CustomObject>
    <description>This is child to Project where users can select a User and can assign a Role as well</description>
    <label>Project Team</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Project Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>check the checkbox if selected user is primary.</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Team__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Lookup to Project to select Project</description>
    <inlineHelpText>Select Project Name Here</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project_Team__c/fields/Project_Role__c.field-meta.xml
<CustomField>
    <fullName>Project_Role__c</fullName>
    <inlineHelpText>Select the role of this user.</inlineHelpText>
    <label>Project Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project Executive</fullName>
            </value>
            <value>
                <fullName>Service Desk Agent</fullName>
            </value>
            <value>
                <fullName>Sr. Project Executive</fullName>
            </value>
            <value>
                <fullName>Service Delivery Executive</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>SDM</fullName>
            </value>
            <value>
                <fullName>Project Management Head</fullName>
            </value>
            <value>
                <fullName>Regional Head Service Delivery</fullName>
            </value>
            <value>
                <fullName>Global delivery Director</fullName>
            </value>
            <value>
                <fullName>Global OPS Head</fullName>
            </value>
            <value>
                <fullName>Resource may have Engineers(Contractor-Dispatch, Contractor-FTE, FTE)</fullName>
            </value>
            <value>
                <fullName>Service Desk Lead</fullName>
            </value>
            <value>
                <fullName>Service Desk Manager</fullName>
            </value>
            <value>
                <fullName>Service Delivery Manager</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Account Director</fullName>
            </value>
            <value>
                <fullName>Client SDM</fullName>
            </value>
            <value>
                <fullName>TIG SDM</fullName>
            </value>
            <value>
                <fullName>RDH</fullName>
            </value>
            <value>
                <fullName>Sales Executive</fullName>
            </value>
            <value>
                <fullName>Pre-Sales Team</fullName>
            </value>
            <value>
                <fullName>Sales Team</fullName>
            </value>
            <value>
                <fullName>AR Execuive</fullName>
            </value>
            <value>
                <fullName>AR Sr. Executive</fullName>
            </value>
            <value>
                <fullName>AR Manager</fullName>
            </value>
            <value>
                <fullName>AR Head</fullName>
            </value>
            <value>
                <fullName>AP Executive</fullName>
            </value>
            <value>
                <fullName>AP Sr. Executive</fullName>
            </value>
            <value>
                <fullName>AP Manager</fullName>
            </value>
            <value>
                <fullName>AP Head</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Team__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Team__c/recordTypes/External.recordType-meta.xml
<RecordType>
    <fullName>External</fullName>
    <active>true</active>
    <label>External</label>
</RecordType>

force-app/main/default/objects/Project_Team__c/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/classes/Billing_Information_Trigger_Handler.cls
/******************************************************
*Class Name: BillingInformationTriggerHandler
*Description
*Date
*Developer Name : Vineet Kumar
******************************************************/
public class Billing_Information_Trigger_Handler {
    
    // This method will check the conditions and will fire the approval for the billing records if conditions are meeting
    public static void submitForApproval(Map<ID,Billing_Information__c>  billingOldVersionMap, List<Billing_Information__c> BillingNewVersionList )
    {           
        List<Approval.ProcessSubmitRequest> requests = new List<Approval.ProcessSubmitRequest>();
        List<Approval.ProcessSubmitRequest> requests2 = new List<Approval.ProcessSubmitRequest>();
        Set<String> prjSet = new Set<String>();
        Map<String,String> InfoMap = new Map<String,String>();
        //    List<Billing_Information__c>  recordsToBeApproved=new List<Billing_Information__c>();
        //collect Client SDM Approvers for  Projects   
        Set<Id> ProjIds=new Set<Id>();
        for(Billing_Information__c info:BillingNewVersionList)
        {
            projIds.add(info.Project__c);
        }
        
        //collect primary external sdm
        List<Project_Team__c> teamPrimaryExternalSDMList=[SELECT User__c,Primary__c,Project__c,Project_Role__c FROM Project_Team__c  WHERE Project__c IN: projIds AND Primary__c=TRUE AND Project_Role__c='SDM' AND RecordType.Name='External'];
        Map<ID,ID> clientSDMApproverMap=new Map<ID,ID>();  // will hold External SDM IDs from projects (Map<Project Id,Primary External SDM Id>)
        if(teamPrimaryExternalSDMList.size()>0)
        {
            for(Project_Team__c pt:teamPrimaryExternalSDMList)
            {
                clientSDMApproverMap.put(pt.Project__c,pt.User__c);
            }
        }
        
        //collect primary internal sdm
        List<Project_Team__c> teamPrimaryInternalSDMList=[SELECT User__c,Primary__c,Project__c,Project_Role__c FROM Project_Team__c  WHERE Project__c IN: projIds AND Primary__c=TRUE AND Project_Role__c='SDM' AND RecordType.Name='Internal'];
        Map<ID,ID> internalSDMApproverMap=new Map<ID,ID>();  // will hold Primary Internal SDM IDs from projects (Map<Project Id,Primary Internal SDM Id>)
        if(teamPrimaryInternalSDMList.size()>0)
        {
            for(Project_Team__c pt:teamPrimaryInternalSDMList)
            {
                internalSDMApproverMap.put(pt.Project__c,pt.User__c);
            }
        }     
        
        for(Billing_Information__c info:BillingNewVersionList)
        {
            system.debug('Account_Type__c===>'+info.Account_Type__c);
            If(info.Account_Type__c == 'Customer' && billingOldVersionMap.get(info.id).Billing_Approval_Status__c!=info.Billing_Approval_Status__c && (info.Billing_Approval_Status__c=='Sent to SDM') )
            {
                If(internalSDMApproverMap.get(info.Project__c)!=NULL)
                {
                    Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                    req1.setComments('Submitting request for billing approval');
                    req1.setObjectId(info.id);
                    req1.setNextApproverIds(new Id[] {internalSDMApproverMap.get(info.Project__c)});
                    requests.add(req1);
                }
                else
                {
                    info.addError(Label.Add_Primary_Internal_SDM_Error_Message);
                }
            }
            else If(info.Account_Type__c == 'Customer' && billingOldVersionMap.get(info.id).Billing_Approval_Status__c!=info.Billing_Approval_Status__c && (info.Billing_Approval_Status__c=='Sent to AR Manager') )
            {
                Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                req1.setComments('Submitting request for billing approval');
                req1.setObjectId(info.id);
                requests.add(req1);
            }
            Else If(info.Account_Type__c == 'Customer' && billingOldVersionMap.get(info.id).Billing_Approval_Status__c!=info.Billing_Approval_Status__c && info.Billing_Approval_Status__c=='Sent to AR Head' )
            {
                Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                req1.setComments('Submitting request for billing approval');
                req1.setObjectId(info.id);
                requests2.add(req1);
                approveRecords(info);
            }
            Else If(info.Account_Type__c == 'Customer' && billingOldVersionMap.get(info.id).Billing_Approval_Status__c!=info.Billing_Approval_Status__c && info.Billing_Approval_Status__c=='Sent to Client SDM' )
            {
                If(clientSDMApproverMap.get(info.Project__c)!=NULL)
                {
                    Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                    req1.setComments('Submitting request for billing approval');
                    req1.setObjectId(info.id);
                    req1.setNextApproverIds(new Id[] {clientSDMApproverMap.get(info.Project__c)});
                    requests2.add(req1);
                    approveRecords(info);
                }
                else
                {
                    info.addError(Label.Add_Primary_External_SDM_Error_Message);
                }
                
            }
            else if(info.Account_Type__c == 'Vendor' && billingOldVersionMap.get(info.id).Billing_Approval_Status__c!=info.Billing_Approval_Status__c && (info.Billing_Approval_Status__c=='Sent to TIG SDM') )
            {
                prjSet.add(info.Project__c);
                InfoMap.put(info.Project__c,info.id);
            }
        }
        
        if(prjSet.size() > 0){
            for(List<Project_Team__c> roleList : [Select User__c,Project__c FROM Project_Team__c WHERE Project__c IN :prjSet AND Project_Role__c = 'Service Desk Manager' AND Primary__c =TRUE LIMIT 1]){
                for(Project_Team__c role:roleList){
                    Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                    req1.setComments('Submitting request for billing approval');
                    system.debug('InfoMap=======>'+InfoMap.get(role.Project__c));
                    system.debug('role=======>'+role.User__c);
                    req1.setObjectId(InfoMap.get(role.Project__c));
                    req1.setNextApproverIds(new Id[] {role.User__c});
                    Approval.ProcessResult result = Approval.process(req1);
                    system.debug('result=======>'+result);
                }
                
            }
        }
        // Submit the approval request.
        system.debug('requests==>'+requests);
        if(requests.size()>0)
        {
            Approval.process(requests); 
        }
        if(requests2.size()>0 )
        {
            Approval.process(requests2); 
        } 
    }
    
    /* This method will throw an error if AR Manager Approves the record with updating the approval status. 
* for this we have a checkbox "Approved by AR Manager"  and it gets checked through approval process 
* and this method checks if that checkbox is checked and approval status is not changed to
* "Sent to AR Head" or "Sent to Client SDM" then will throw error while approving the record */
    public static void checkApprovalStatus(Map<ID,Billing_Information__c>  billingOldVersionMap, List<Billing_Information__c> BillingNewVersionList)
    {
        for(Billing_Information__c bi:BillingNewVersionList)
            if(billingOldVersionMap.get(bi.id).Approved_by_AR_Manager__c!=bi.Approved_by_AR_Manager__c && bi.Approved_by_AR_Manager__c==True && bi.Billing_Approval_Status__c=='Sent to AR Manager')
        {
            bi.addError(Label.Submit_to_AR_Head_or_Client_SDM);
        }
    }
    
    /*
* This method will Approve the Billing 
*/
    
    public static void approveRecords(Billing_Information__c record)
    {
        // List<Approval.ProcessWorkitemRequest>  pwr=new List<Approval.ProcessWorkitemRequest>();
        //  for(Billing_Information__c bi:records)
        // {
        //Class used for Approving Record
        Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
        req.setComments('Approving request for Billing');
        
        //Approve or Reject Record
        req.setAction('Approve');
        
        //Getting Work Item Id
        ProcessInstanceWorkitem pItem = [Select Id from ProcessInstanceWorkitem 
                                         where ProcessInstance.TargetObjectId =: record.id];
        if(pItem!=NULL)
        {
            req.setWorkitemId(pItem.Id);
            System.debug('Req :'+req);
            // pwr.add(req);
            //  }
            // Submit the request for approval
            Approval.ProcessResult result = Approval.process(req);
        }
        
    }
    
    
    // this method contains the logic for making comment mandatory on billing approval/rejection
    public static void approvalCommentRequired(List<Billing_Information__c>  billingRecords)
    {
        // Create a map that stores all the objects that require editing 
        Map<Id, Billing_Information__c> approvalStatements = 
            new Map<Id, Billing_Information__c>{};
                
                for(Billing_Information__c bi: billingRecords)
            {
                // Put all objects for update that require a comment check in a map,
                // so we only have to use 1 SOQL query to do all checks
                
                if (bi.Approval_Comment_Check__c == 'Requested')
                { 
                    approvalStatements.put(bi.Id, bi);
                    // Reset the field value to null, 
                    // so that the check is not repeated,
                    // next time the object is updated
                    bi.Approval_Comment_Check__c = null; 
                }
            }  
        
        if (!approvalStatements.isEmpty())  
        {
            // UPDATE 2/1/2014: Get the most recent process instance for the approval.
            // If there are some approvals to be reviewed for approval, then
            // get the most recent process instance for each object.
            List<Id> processInstanceIds = new List<Id>{};
                List<Billing_Information__c>  BilRecords=[SELECT (SELECT ID
                                                                  FROM ProcessInstances
                                                                  ORDER BY CreatedDate DESC
                                                                  LIMIT 1)
                                                          FROM Billing_Information__c
                                                          WHERE ID IN :approvalStatements.keySet()];
            if(BilRecords.size()>0)
            {
                for (Billing_Information__c bir : BilRecords)
                {
                    if(bir.ProcessInstances.size()>0)
                    {
                        processInstanceIds.add(bir.ProcessInstances[0].Id);
                    }
                }
                
                // Now that we have the most recent process instances, we can check
                // the most recent process steps for comments.  
                for (ProcessInstance pi : [SELECT TargetObjectId,
                                           (SELECT Id, StepStatus, Comments 
                                            FROM Steps
                                            ORDER BY CreatedDate DESC
                                            LIMIT 1 )
                                           FROM ProcessInstance
                                           WHERE Id IN :processInstanceIds
                                           ORDER BY CreatedDate DESC])
                {
                    // If no comment exists, then prevent the object from saving.                 
                    if ((pi.Steps[0].Comments == null || 
                         pi.Steps[0].Comments.trim().length() == 0))
                    {
                        approvalStatements.get(pi.TargetObjectId).addError(
                            'Operation Cancelled: Please provide a reason ' + 
                            'for your approval / rejection!');
                    }
                }       
            }
        }
    } 
    
    
    /*   public static Set<Id> getApprover(ID prjId,String role)
{
system.debug('prjId'+prjId);
Set<Id> ApproverIds = new Set<Id>();
List<Project_Team__c> roleList = new List<Project_Team__c>();
if(prjId != null && role != ''){
roleList = [Select User__c from Project_Team__c where Project__c = :prjId AND Project_Role__c =:role limit 5];
//UserIds.add();
system.debug('roleList'+roleList);
for(Project_Team__c rList:roleList){
ApproverIds.add(rList.User__c);
}
}
return ApproverIds;
}  */
    /*public static void approvedRecord(String recId,Id prjId,String role){
List<Approval.ProcessSubmitRequest> requests = new List<Approval.ProcessSubmitRequest>();	
Set<ID> ApproverIds = new Set<ID>();
ApproverIds = getApprover(prjId,role);
Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
for(ID approverId:ApproverIds){
req.setComments('Approving request using Trigger');
req.setAction('Approve');
req.setNextApproverIds(new Id[] {approverId});
Id workItemId = getWorkItemId(recId);
req.setWorkitemId(workItemId);
requests.add(req);
}
// Submit the request for approval
Approval.ProcessResult result =  Approval.process(req);
}
public static Id getWorkItemId(Id targetObjectId)
{
Id retVal = null;
for(ProcessInstanceWorkitem workItem  : [Select p.Id from ProcessInstanceWorkitem p
where p.ProcessInstance.TargetObjectId =: targetObjectId])
{
retVal  =  workItem.Id;
}
return retVal;
}*/
    
}