force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Billing_Information__c/Billing_Information__c.object-meta.xml
<CustomObject>
    <description>This will hold billing related information for a project.</description>
    <label>Billing Information</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Information</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Information__c/fields/Approved_by_AR_Manager__c.field-meta.xml
<CustomField>
    <fullName>Approved_by_AR_Manager__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used internally in Billing Approval Process</description>
    <label>Approved by AR Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Information__c/fields/Billing_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Billing_Approval_Status__c</fullName>
    <description>will hold status of the approval</description>
    <label>Billing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upload Raw  Data</fullName>
                <default>true</default>
                <label>Upload Raw  Data</label>
            </value>
            <value>
                <fullName>Sent to SDM</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
            <value>
                <fullName>Sent to AR Executive/ AR Sr. Executive</fullName>
            </value>
            <value>
                <fullName>Sent to AR Manager</fullName>
            </value>
            <value>
                <fullName>Sent to AR Head</fullName>
            </value>
            <value>
                <fullName>Sent to Client SDM</fullName>
            </value>
            <value>
                <fullName>Sent to TIG SDM</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Billing Approved</fullName>
            </value>
            <value>
                <fullName>Rejected by AR Executive/ AR Sr. Executive</fullName>
                <isActive>false</isActive>
                <label>Rejected by AR Executive/ AR Sr. Executive</label>
            </value>
            <value>
                <fullName>Rejected by AR Head</fullName>
                <isActive>false</isActive>
                <label>Rejected by AR Head</label>
            </value>
            <value>
                <fullName>Rejected by AR Manager</fullName>
                <isActive>false</isActive>
                <label>Rejected by AR Manager</label>
            </value>
            <value>
                <fullName>Rejected by Client SDM</fullName>
                <isActive>false</isActive>
                <label>Rejected by Client SDM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Information__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>Project__r.Customer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Information__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Billing Information</relationshipLabel>
    <relationshipName>Billing_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Information__c/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Half-Yearly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>ADHOC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer/Vendor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects12</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>End Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (End Customer)</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Project_Team__c/Project_Team__c.object-meta.xml
<CustomObject>
    <description>This is child to Project where users can select a User and can assign a Role as well</description>
    <label>Project Team</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Project Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Lookup to Project to select Project</description>
    <inlineHelpText>Select Project Name Here</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project_Team__c/recordTypes/External.recordType-meta.xml
<RecordType>
    <fullName>External</fullName>
    <active>true</active>
    <label>External</label>
</RecordType>

force-app/main/default/objects/Project_Team__c/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/classes/Billing_Information_Trigger_Handler_Test.cls
@isTest
public class Billing_Information_Trigger_Handler_Test {
    
    @TestSetup
    public static void testDataCreation()
    {
        Account acc= Test_Data_Factory.createAccount('Customer');
        insert acc;
        Contact con=Test_Data_Factory.createContact();
        insert con;
        
        Project__c projOneTime=Test_Data_Factory.createProject('One Time','Customer');
        projOneTime.Customer__c=acc.id;
        projOneTime.End_Customer__c=acc.id;
        insert projOneTime;
        
        Project__c weekly=Test_Data_Factory.createProject('Weekly','Customer');
        weekly.Customer__c=acc.id;
        weekly.End_Customer__c=acc.id;
        insert weekly;
        
        /*   Billing_Information__c bill=Test_Data_Factory.createBillingInformation();
bill.Project__c=projOneTime.id;
insert bill;  */
        
        Project_Team__c pt=Test_Data_Factory.createProjectTeam('Internal',True);
        pt.Project__c=projOneTime.Id;
        insert pt;
        
        Project_Team__c pt1=Test_Data_Factory.createProjectTeam('External',True);
        pt1.Project__c=projOneTime.Id;
        insert pt1;    
        
        /*  Project_Team__c pt2=Test_Data_Factory.createProjectTeam('External',True);
pt2.Project__c=weekly.Id;
insert pt2; */
    }
    
    public TestMethod static void testBillingApproval1()
    {
        try{
            Billing_Information__c bi=[Select id from Billing_Information__c where Project__r.Billing_Frequency__c='One Time'];
            bi.Billing_Approval_Status__c='Sent to AR Manager';
            bi.Approved_by_AR_Manager__c=true;
            update bi;
        }Catch(Exception ex)
        {
            System.Assert(ex.getMessage().contains(Label.Submit_to_AR_Head_or_Client_SDM));
            
        }
        
        Billing_Information__c bi=[Select id from Billing_Information__c where Project__r.Billing_Frequency__c='One Time'];
        bi.Billing_Approval_Status__c='Sent to AR Manager';
        update bi;
        
        Billing_Information__c bi1=[Select id from Billing_Information__c where Project__r.Billing_Frequency__c='One Time'];
        bi1.Billing_Approval_Status__c='Sent to AR Head';
        update bi1;
        
        Billing_Information__c bi2=[Select id from Billing_Information__c where Project__r.Billing_Frequency__c='One Time'];
        bi2.Billing_Approval_Status__c='Sent to Client SDM';
        update bi2;
        
    }
    
    public TestMethod static void testBillingApproval2()
    {      
        Try{
            Billing_Information__c weeklyBilling1=[Select id from Billing_Information__c where Project__r.Billing_Frequency__c='Weekly'];
            weeklyBilling1.Billing_Approval_Status__c='Sent to AR Manager';
            update weeklyBilling1; 
            
            Billing_Information__c weeklyBilling2=[Select id from Billing_Information__c where Project__r.Billing_Frequency__c='Weekly'];
            weeklyBilling2.Billing_Approval_Status__c='Sent to Client SDM';
            update weeklyBilling2;
        }Catch(Exception ex)
        {
            System.Assert(ex.getMessage().contains(Label.Add_Primary_Internal_SDM_Error_Message));
            
        }
    }
}