force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Half-Yearly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>ADHOC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer/Vendor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects12</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>End Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (End Customer)</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Project_Team__c/Project_Team__c.object-meta.xml
<CustomObject>
    <description>This is child to Project where users can select a User and can assign a Role as well</description>
    <label>Project Team</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Project Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>check the checkbox if selected user is primary.</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Team__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Lookup to Project to select Project</description>
    <inlineHelpText>Select Project Name Here</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project_Team__c/fields/Project_Role__c.field-meta.xml
<CustomField>
    <fullName>Project_Role__c</fullName>
    <inlineHelpText>Select the role of this user.</inlineHelpText>
    <label>Project Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project Executive</fullName>
            </value>
            <value>
                <fullName>Service Desk Agent</fullName>
            </value>
            <value>
                <fullName>Sr. Project Executive</fullName>
            </value>
            <value>
                <fullName>Service Delivery Executive</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>SDM</fullName>
            </value>
            <value>
                <fullName>Project Management Head</fullName>
            </value>
            <value>
                <fullName>Regional Head Service Delivery</fullName>
            </value>
            <value>
                <fullName>Global delivery Director</fullName>
            </value>
            <value>
                <fullName>Global OPS Head</fullName>
            </value>
            <value>
                <fullName>Resource may have Engineers(Contractor-Dispatch, Contractor-FTE, FTE)</fullName>
            </value>
            <value>
                <fullName>Service Desk Lead</fullName>
            </value>
            <value>
                <fullName>Service Desk Manager</fullName>
            </value>
            <value>
                <fullName>Service Delivery Manager</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Account Director</fullName>
            </value>
            <value>
                <fullName>Client SDM</fullName>
            </value>
            <value>
                <fullName>TIG SDM</fullName>
            </value>
            <value>
                <fullName>RDH</fullName>
            </value>
            <value>
                <fullName>Sales Executive</fullName>
            </value>
            <value>
                <fullName>Pre-Sales Team</fullName>
            </value>
            <value>
                <fullName>Sales Team</fullName>
            </value>
            <value>
                <fullName>AR Execuive</fullName>
            </value>
            <value>
                <fullName>AR Sr. Executive</fullName>
            </value>
            <value>
                <fullName>AR Manager</fullName>
            </value>
            <value>
                <fullName>AR Head</fullName>
            </value>
            <value>
                <fullName>AP Executive</fullName>
            </value>
            <value>
                <fullName>AP Sr. Executive</fullName>
            </value>
            <value>
                <fullName>AP Manager</fullName>
            </value>
            <value>
                <fullName>AP Head</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Team__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Team__c/recordTypes/External.recordType-meta.xml
<RecordType>
    <fullName>External</fullName>
    <active>true</active>
    <label>External</label>
</RecordType>

force-app/main/default/objects/Project_Team__c/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/classes/Project_Team_Trigger_Handler_Test.cls
@isTest
public class Project_Team_Trigger_Handler_Test {
    
    @TestSetup
    public static void testDataCreation()
    {
        Account acc= Test_Data_Factory.createAccount('Customer');
        insert acc;
        Contact con=Test_Data_Factory.createContact();
        insert con;
        
        Project__c projOneTime=Test_Data_Factory.createProject('One Time','Customer');
        projOneTime.Customer__c=acc.id;
        projOneTime.End_Customer__c=acc.id;
        projOneTime.Billing_Frequency__c='One Time';
        insert projOneTime;
        
        Project__c Weekly=Test_Data_Factory.createProject('Weekly','Customer');
        Weekly.Customer__c=acc.id;
        Weekly.End_Customer__c=acc.id;
        Weekly.Billing_Frequency__c='Weekly';
        insert Weekly;        
        System.debug('projId :'+Weekly.id);
        
        List<Project_Team__c> teamList=new List<Project_Team__c>();
        Project_Team__c pt=Test_Data_Factory.createProjectTeam('Internal', False);
        pt.Project__c=projOneTime.Id;
        insert pt;
        Project_Team__c pt1=Test_Data_Factory.createProjectTeam('Internal', true);
        pt1.Project__c=projOneTime.Id;
        insert pt1;
        
    }
    
    public static TestMethod void TestFirstDefaultPrimary()
    {
        List<Project_Team__c> teamList=[Select RecordTypeId,RecordType.Name,User__c,Project_Role__c,Project__c, Primary__c FROM Project_Team__c];
        Project_Team_Trigger_Handler.firstDefaultPrimary(teamList);
    }
    
    public static TestMethod void testUpdatePrimaryProjectTeamMember()
    {
        List<Project_Team__c> teamList=[Select RecordTypeId,RecordType.Name,User__c,Project_Role__c,Project__c, Primary__c FROM Project_Team__c where primary__C=false limit 1];
        Project_Team__c pt=teamList[0];
        pt.Primary__c=true;
        update pt;
        
    }
    
    public TestMethod static void  testMethod1()
    {
        Project__c Weekly=Test_Data_Factory.createProject('Weekly','Customer');
        Weekly.Customer__c=[select id from Account limit 1].id;
        Weekly.End_Customer__c=[select id from Account limit 1].id;
        Weekly.Billing_Frequency__c='Weekly';
        insert Weekly;        
        
        System.debug('projId :'+Weekly.id);       // Project_Team_Trigger_Handler.updatePrimaryProjectTeamMember(teamList, NULL);
        Project_Team__c pt1=Test_Data_Factory.createProjectTeam('Internal', false);
        pt1.Project__c=Weekly.Id;
        insert pt1; 
        
        Project_Team__c pt2=Test_Data_Factory.createProjectTeam('Internal', false);
        pt2.Project__c=Weekly.Id;
        insert pt2; 
        Project_Team__c pt3=Test_Data_Factory.createProjectTeam('External', false);
        pt3.Project__c=Weekly.Id;
        insert pt3;  
        
        Project_Team__c pt4=Test_Data_Factory.createProjectTeam('External', false);
        pt4.Project__c=Weekly.Id;
        insert pt4;           
        List<Project_Team__c> ptList= [SELECT id from Project_Team__c where Project__c =:Weekly.id AND Primary__c=FALSE];
        List<Project_Team__c> teamList=new List<Project_Team__c>();
        for(Project_Team__c pt:ptList)
        {
            pt.Primary__c=true;
            teamList.add(pt);
            
        }
        
        update teamList;
    }
    
    public TestMethod static void  testMethod2()
    {
        Project__c Weekly=Test_Data_Factory.createProject('Weekly','Customer');
        Weekly.Customer__c=[select id from Account limit 1].id;
        Weekly.End_Customer__c=[select id from Account limit 1].id;
        Weekly.Billing_Frequency__c='Weekly';
        insert Weekly;        
        
        Project__c Weekly1=Test_Data_Factory.createProject('Weekly','Customer');
        Weekly1.Customer__c=[select id from Account limit 1].id;
        Weekly1.End_Customer__c=[select id from Account limit 1].id;
        Weekly1.Billing_Frequency__c='Weekly';
        insert Weekly1;  
        
        System.debug('projId :'+Weekly.id);       // Project_Team_Trigger_Handler.updatePrimaryProjectTeamMember(teamList, NULL);
        Project_Team__c pt1=Test_Data_Factory.createProjectTeam('Internal', false);
        pt1.Project__c=Weekly.Id;
        insert pt1; 
        
        Project_Team__c pt2=Test_Data_Factory.createProjectTeam('Internal', false);
        pt2.Project__c=Weekly.Id;
        
        Project_Team__c pt3=Test_Data_Factory.createProjectTeam('Internal', false);
        pt3.Project_Role__c='Project Manager';
        pt3.Project__c=Weekly.Id;
        
        Project_Team__c pt4=Test_Data_Factory.createProjectTeam('Internal', false);
        pt4.Project__c=Weekly1.Id;
        
        List<Project_Team__c>  teamList=new List<Project_Team__c>();
        teamList.add(pt2);
        teamList.add(pt3);
        teamList.add(pt4);
        insert teamList;
    }
    
    
}