force-app/main/default/objects/Account/fields/Captured_through_Vendor_Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Captured_through_Vendor_Enquiry__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It will be true if the vendor is created through vendor enquiry form and then converted into vendor record.</description>
    <label>Captured through Vendor Enquiry?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Bank Country</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/One_Time_Vendor__c.field-meta.xml
<CustomField>
    <fullName>One_Time_Vendor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>One Time Vendor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>NDA Signed</fullName>
            </value>
            <value>
                <fullName>Due Diligence</fullName>
            </value>
            <value>
                <fullName>Sent for Approval</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Request for Deactivation</fullName>
                <label>Request for DeActivation</label>
            </value>
            <value>
                <fullName>DeActivation Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Vendor_Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Enquiry</label>
    <referenceTo>Vendor_Enquiry__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vendor_Enquiry_Id__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Enquiry_Id__c</fullName>
    <label>Vendor Enquiry Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/Vendor_Enquiry__c/Vendor_Enquiry__c.object-meta.xml
<CustomObject>
    <label>Vendor Enquiry</label>
    <nameField>
        <label>Vendor Enquiry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor_Enquiry</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Enquiry__c/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <inlineHelpText>Please provide a valid contact number.</inlineHelpText>
    <label>Contact number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Vendor_Enquiry__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <inlineHelpText>Please provide Country name.</inlineHelpText>
    <label>Country</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor_Enquiry__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <inlineHelpText>Please enter your first name</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor_Enquiry__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <inlineHelpText>Please enter your lastname</inlineHelpText>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor_Enquiry__c/fields/Name_of_the_Organization__c.field-meta.xml
<CustomField>
    <fullName>Name_of_the_Organization__c</fullName>
    <inlineHelpText>Please provide Company/Organization name.</inlineHelpText>
    <label>Name of the Organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor_Enquiry__c/fields/Official_Email_id__c.field-meta.xml
<CustomField>
    <fullName>Official_Email_id__c</fullName>
    <inlineHelpText>Please provide a valid mail address.</inlineHelpText>
    <label>Official Email id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Vendor_Enquiry__c/fields/One_Time_Vendor__c.field-meta.xml
<CustomField>
    <fullName>One_Time_Vendor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Please check this check box if vendor is one time vendor.</description>
    <inlineHelpText>Please check this check box if vendor is one time vendor.</inlineHelpText>
    <label>One Time Vendor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vendor_Enquiry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>It tell us the status of vendor.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Selected for Onboarding</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VendorEnquiryHandler.cls
public class VendorEnquiryHandler {
    public void createAccCon(List<Vendor_Enquiry__c> lstNewVE){
        //Account and Contact Insertion 
        Boolean isAccountCreate=false;
        list<sobject> sObjList = new list<sObject>();
        Id vendorRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Vendor').getRecordTypeId();
        system.debug('recordType Id --> ' + vendorRecordTypeId);
        for(Vendor_Enquiry__c vendorRec: lstNewVE){
            if(vendorRec.Status__c == 'Selected for Onboarding'){
                Account acc = new Account();
                acc.name = vendorRec.Name_of_the_Organization__c;
                acc.Status__c ='Initiation';
                acc.RecordTypeId = vendorRecordTypeId;
                acc.Vendor_Enquiry_Id__c = vendorRec.Name;
                acc.Captured_through_Vendor_Enquiry__c=TRUE;
                acc.Vendor_Enquiry__c=vendorRec.Id;
                acc.One_Time_Vendor__c=vendorRec.One_Time_Vendor__c;
                sObjList.add(acc);
            }
            if(!sObjList.isEmpty()){
                insert sObjList;
                isAccountCreate=true;
            }
            
        }
        list<sobject> sObjListCon = new list<sObject>();
        for(Vendor_Enquiry__c vendorRec1: lstNewVE){
            if(vendorRec1.Status__c == 'Selected for Onboarding'){
                for(sObject accList:sObjList){
                    Contact con = new Contact();
                    con.LastName = vendorRec1.Last_Name__c;
                    con.FirstName = vendorRec1.First_Name__c;
                    con.AccountId = accList.Id;
                    con.Email = vendorRec1.Official_Email_id__c;
                    con.MobilePhone = vendorRec1.Contact_number__c;
                    con.MailingCountry = vendorRec1.Country__c;
                    sObjListCon.add(con);
                    
                }
            }
            if(!sObjListCon.isEmpty()){
                insert sObjListCon;
            }
            
        }
        
        List<String> conIds = new List<String>();
        for(sObject conRecId:sObjListCon){
            conIds.add(conRecId.Id);
            system.debug('ContactIds--->'+conIds);
        }
        //get the AccountContact Role
        // List<AccountContactRole> acr = [Select Id, accountId, ContactId, Role from AccountContactRole where contactId IN:conIds];
        //system.debug('acr--->' +acr);
        
        /*
list<sobject> sObjListRole = new list<sObject>();
for(Vendor_Enquiry__c vendorRec1: lstNewVE){
system.debug('vendorRec1--->'+vendorRec1);
if(vendorRec1.Status__c == 'Selected for Onboarding'){
for(sObject accList:sObjList){
system.debug('accList--->'+accList);
for(sObject conList:sObjListCon){
system.debug('conList--->'+conList);
AccountContactRole acr = new AccountContactRole();
acr.AccountId = accList.Id;
acr.ContactId = conList.Id;
acr.Role = 'Other';
sObjListRole.add(acr);
}
}
}
system.debug('sObjListRole---->'+sObjListRole);
update sObjListRole;
}*/
        //Fiels Transer 
        if(isAccountCreate)
        {
            Set<ID> VendorRecIds = new Set<ID>();
            List<String> VendorName = new List<String>();
            for(Vendor_Enquiry__c vendorRec: lstNewVE){
                VendorRecIds.add(vendorRec.Id);
                VendorName.add(vendorRec.Name);
            }
            Account accList = [SELECT Id, name, Vendor_Enquiry_Id__c FROM Account WHERE Vendor_Enquiry_Id__c=:VendorName limit 1];
            system.debug('accList------->'+accList);
            List<ContentDocumentLink> cDL= [SELECT Id, ContentDocumentId, ContentDocument.Title, ContentDocument.ContentModifiedDate, 
                                            ContentDocument.LatestPublishedVersion.Document_Type__c, ContentDocument.LatestPublishedVersionId,
                                            ContentDocument.LatestPublishedVersion.ContentModifiedBy.Name
                                            FROM ContentDocumentLink WHERE LinkedEntityId =: VendorRecIds];
            List<ContentDocumentLink> filesLst = new List<ContentDocumentLink>();
            for(ContentDocumentLink cDList:cDL){
                ContentDocumentLink cDLRec = new ContentDocumentLink();
                cDLRec.ContentDocumentId = cDList.ContentDocumentId;
                cDLRec.LinkedEntityId = accList.Id;
                
                filesLst.add(cDLRec);   
            } 
            insert filesLst;   
            
            //Tasks
            List<Task> ts_List = new List<Task>();
            List<Task> ts_List1 = new List<Task>();
            List<Task> taskList = [SELECT Id, whatId, Subject, ActivityDate FROM Task where whatId =: VendorRecIds LIMIT 1];
            for(Task taskRecIntro: taskList){
                Task newTaskRec = new Task();
                //newTaskRec.Id = taskRecIntro.Id;
                newTaskRec.whatId = accList.Id;
                newTaskRec.Subject = 'Introduction call';
                newTaskRec.ActivityDate = system.Today()+7;
                //newTaskRec.ActivityDate = system.Today()+7;
                ts_List.add(newTaskRec);
            }
            insert ts_List;
            List<Task> taskList1 = [SELECT Id, whatId, Subject, ActivityDate FROM Task where whatId =: VendorRecIds];
            for(Task taskRec: taskList1){
                Task newTaskRec = new Task();
                newTaskRec.Id = taskRec.Id;
                newTaskRec.whatId = accList.Id;
                newTaskRec.Subject = taskRec.subject;
                newTaskRec.ActivityDate = taskRec.ActivityDate;
                //newTaskRec.ActivityDate = system.Today()+7;
                ts_List1.add(newTaskRec);
            }
            upsert ts_List1;
        }
        
    }
}