force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>NDA Signed</fullName>
            </value>
            <value>
                <fullName>Due Diligence</fullName>
            </value>
            <value>
                <fullName>Sent for Approval</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Request for Deactivation</fullName>
                <label>Request for DeActivation</label>
            </value>
            <value>
                <fullName>DeActivation Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Check SOW &amp; PO</fullName>
            </value>
            <value>
                <fullName>Validate Invoice</fullName>
            </value>
            <value>
                <fullName>Review and Update Taxation</fullName>
            </value>
            <value>
                <fullName>Invoice Ready to be Sent to Client</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Exception Approval Needed</fullName>
            </value>
            <value>
                <fullName>Send to Department Head</fullName>
            </value>
            <value>
                <fullName>Send to C Group</fullName>
            </value>
            <value>
                <fullName>Sent To Client</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApprovalService.cls
public class ApprovalService {
    
    
    /*@InvocableMethod
	public static void escalateToTIGDelivery(List<ID> invIds){
        List<Invoice__c> unattendetInvoice = [Select ID, status__c from Invoice__c WHERE id =: invIds[0]];
        
        if(unattendetInvoice[0].status__c == 'Send To TIG SDM'){
            ApprovalService service = new ApprovalService();
            service.rejectApprovalRecord(invIds, 'Escalated to TIG Delivery');
            Invoice__c inv = new Invoice__c();
            inv.id= invIds[0];
            inv.Status__c = 'Send To TIG Delivery';
            
            update inv;
            
            InvoiceHandler handler = new InvoiceHandler();
            
            
            service.submitforApproval('Send_To_TIG_Delivery', 'Submitting request for approval.', inv.id, new List<String>{handler.roleMap.get('Client SDM')});        
        }else if(unattendetInvoice[0].status__c == 'Sent to AP Executive/Sr. Executive'){
            ApprovalService service = new ApprovalService();
            service.approveApprovalRecord(invIds, 'Auto Approve');
        }       
     
     }*/
    
    public void rejectApprovalRecord(List<ID> invIds, string comment){
         //Class used for Approving Record
         Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
         req.setComments(comment);
         
         //Approve or Reject Record
         req.setAction('Reject');
         
         //Getting Work Item Id
         ProcessInstanceWorkitem pItem = [Select Id from ProcessInstanceWorkitem where ProcessInstance.TargetObjectId =: invIds[0]];
        
         req.setWorkitemId(pItem.Id);
         // Submit the request for approval
         Approval.ProcessResult result = Approval.process(req);
     
     }
    
    public void approveApprovalRecord(List<ID> invIds, string comment){
         //Class used for Approving Record
         Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
         req.setComments(comment);
         
         //Approve or Reject Record
         req.setAction('Approve');
         
         //Getting Work Item Id
         ProcessInstanceWorkitem pItem = [Select Id from ProcessInstanceWorkitem where ProcessInstance.TargetObjectId =: invIds[0]];
        
         req.setWorkitemId(pItem.Id);
         // Submit the request for approval
         Approval.ProcessResult result = Approval.process(req);
     
     }
    
    public void submitforApproval(string approvalName, string comments, string objID, List<String> nextAppIDs){
        System.debug(nextAppIDs);
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments(comments);
        req1.setObjectId(objID);
        
        // Submit the record to specific process and skip the criteria evaluation
        req1.setProcessDefinitionNameOrId(approvalName);
        req1.setNextApproverIds(nextAppIDs);
        
        // Submit the approval request for the account
        Approval.ProcessResult result = Approval.process(req1);
    }
}