force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>NDA Signed</fullName>
            </value>
            <value>
                <fullName>Due Diligence</fullName>
            </value>
            <value>
                <fullName>Sent for Approval</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Request for Deactivation</fullName>
                <label>Request for DeActivation</label>
            </value>
            <value>
                <fullName>DeActivation Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Type_of_Partner__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Partner__c</fullName>
    <label>Type of Partner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>Payroll Engineers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Custom Order Object</description>
    <label>TIG Order</label>
    <nameField>
        <label>PO Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Bill_to_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Address__c</fullName>
    <label>Bill to Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <formula>TEXT(Project__r.Billing_Frequency__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing Frequency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer/Vendor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4 AND 6) OR (3 AND 5 AND 6)</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sales Order</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Purchase Order</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Indirect Purchase Order</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Sales_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Customer_Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Purchase Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sales Order</value>
        </filterItems>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>startsWith</operation>
            <valueField>Order__c.Customer_Purchase_Order__r.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Vendor Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Delivery_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Instructions__c</fullName>
    <label>Delivery Instructions</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/PO_Amount__c.field-meta.xml
<CustomField>
    <fullName>PO_Amount__c</fullName>
    <label>PO Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/PO_End_Date__c.field-meta.xml
<CustomField>
    <fullName>PO_End_Date__c</fullName>
    <label>PO End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/PO_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>PO_Start_Date__c</fullName>
    <label>PO Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Ready_to_Close__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_Close__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The project Owner will mark this field if a task is assigned to him and untill PO Status = Released this field cannot be marked

Remarks: Project Owner can be of profile(Finance, Project Management, Service Delivery,  Admin)</description>
    <label>Ready to Close</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Ship_to_Address__c.field-meta.xml
<CustomField>
    <fullName>Ship_to_Address__c</fullName>
    <label>Ship to Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Vendor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>used for releasing po purpose, Email is sent to this contact once po is realeased</description>
    <label>Vendor Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Half-Yearly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>ADHOC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer/Vendor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects12</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Customer_Project__c.field-meta.xml
<CustomField>
    <fullName>Customer_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Vendor Projects</relationshipLabel>
    <relationshipName>Customer_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>End Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (End Customer)</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/TIG_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>TIG_Entity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TIG Entity Name</label>
    <referenceTo>TIG_Entity__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_PO_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_PO_Amount__c</fullName>
    <description>This will update the Total Purchase Order amount on Vendor Project in a given Fiscal Year and we&apos;re updating it by Apex</description>
    <inlineHelpText>Total Amount of Purchase Orders associated with a Vendor Project in a given Fiscal Year</inlineHelpText>
    <label>Total PO Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Vendor_Projects_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Vendor_Projects_Amount__c</fullName>
    <description>This will update the Total Vendor Projects amount on Customer Project Layout in a given Fiscal Year and we&apos;re updating it by Apex</description>
    <inlineHelpText>Total Vendor Projects Amount  associated with a Customer Project in current Fiscal Year</inlineHelpText>
    <label>Total Vendor Projects Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Project__c/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/TIG_Entity__c/TIG_Entity__c.object-meta.xml
<CustomObject>
    <label>TIG Entity</label>
    <nameField>
        <label>TIG Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TIG Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Task_Trigger_Handler_Test.cls
@isTest
public class Task_Trigger_Handler_Test {
    
    @TestSetup
    public static void testDataCreation(){
       	list<Task> ListofTasks = new list<Task>();
        Account venAcc= Test_Data_Factory.createAccount('Vendor');
      	venAcc.Type_of_Partner__c = 'Contractor';
       	venAcc.Status__c = 'Active';
        venAcc.BillingStreet = 'Old';
        venAcc.BillingCity = 'Kaithal';
        venAcc.BillingState = 'Haryana';
        venAcc.BillingPostalCode = '136027';
        venAcc.BillingCountry = 'India';
        venAcc.ShippingStreet = 'Test';
        venAcc.ShippingCity = 'Siwan';
        venAcc.ShippingState = 'Haryana';
        venAcc.ShippingPostalCode = '136027';
        venAcc.ShippingCountry = 'India';
        insert venAcc;
        
        Account cusAcc= Test_Data_Factory.createAccount('Customer');
        insert cusAcc;
        
        Contact con=Test_Data_Factory.createContact();
        con.AccountId = venAcc.Id;
        con.MobilePhone = '9090909889';
        insert con;
        
        TIG_Entity__c tig = Test_Data_Factory.createTIGEntity();
        insert tig;
        
        Project__c cusProjMonthly=Test_Data_Factory.createProject('Monthly','Customer');
        cusProjMonthly.Customer__c=cusAcc.Id;
        cusProjMonthly.End_Customer__c=cusAcc.Id;
        cusProjMonthly.Total_Vendor_Projects_Amount__c = 100;
        cusProjMonthly.TIG_Entity_Name__c = tig.Id;
        cusProjMonthly.Billing_Frequency__c='Monthly';
        insert cusProjMonthly;
        
        Project__c venProjMonthly=Test_Data_Factory.createProject('Monthly','Vendor');
        venProjMonthly.Customer__c = venAcc.Id;
        venProjMonthly.Customer_Project__c = cusProjMonthly.Id;
        venProjMonthly.TIG_Entity_Name__c = tig.Id;
        venProjMonthly.Total_PO_Amount__c = 100;
        venProjMonthly.Billing_Frequency__c='Monthly';
        insert venProjMonthly; 
        
        Order__c sOr = Test_Data_Factory.createOrder('Sales Order');
        sOr.Customer__c = cusAcc.Id;
        sOr.Project__c = cusProjMonthly.Id;
       	sOr.PO_Start_Date__c=system.today();
        sOr.PO_End_Date__c=system.today()+4;
       	sOr.PO_Amount__c = 200;
        sOr.Bill_to_Address__c = 'Address';
        sOr.Ship_to_Address__c = 'shipTo';
        insert sOr;

        
        Order__c pOr = Test_Data_Factory.createOrder('Purchase Order');
        pOr.Customer__c =venAcc.Id;
        pOr.Vendor_Contact__c = con.Id;
        pOr.Project__c =venProjMonthly.Id;
       	pOr.PO_Start_Date__c=system.today()+1;
        pOr.PO_End_Date__c=system.today()+2;
        pOr.CurrencyIsoCode = 'USD';
        pOr.Ready_to_Close__c = False;
       	pOr.PO_Amount__c = 100;
       // pOr.Fiscal_Year__c = Date.Today().Year();
        pOr.Customer_Purchase_Order__c = sOr.Id;
        pOr.Delivery_Instructions__c = 'Delivery';
        pOr.Ship_to_Address__c = 'Shipping';
            insert pOr;
        
        Task tsk = New Task();
        tsk.OwnerId = UserInfo.getUserId();
        tsk.Status = 'Completed';
        tsk.Subject = 'PO Closure request by Finance Team';
        tsk.ActivityDate = Date.today().addDays(5);
        tsk.Priority = 'High';
        tsk.CurrencyIsoCode = pOr.CurrencyIsoCode;
        tsk.WhatId = pOr.Id;
        insert tsk;
        ListofTasks.add(tsk);
        
    }
    public static TestMethod void testTaskTriggerHandler(){
        TaskTriggerHandler.updateFieldOnPO([Select WhatId, Status, Subject, Priority, ActivityDate, OwnerId, CurrencyIsoCode, Description From Task]);
        
    }
}