force-app/main/default/objects/Account/fields/Type_of_Partner__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Partner__c</fullName>
    <label>Type of Partner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>Payroll Engineers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Custom Order Object</description>
    <label>TIG Order</label>
    <nameField>
        <label>PO Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Bill_to_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Address__c</fullName>
    <label>Bill to Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <formula>TEXT(Project__r.Billing_Frequency__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing Frequency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer/Vendor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4 AND 6) OR (3 AND 5 AND 6)</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sales Order</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Purchase Order</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Indirect Purchase Order</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Sales_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/PO_Amount__c.field-meta.xml
<CustomField>
    <fullName>PO_Amount__c</fullName>
    <label>PO Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/PO_End_Date__c.field-meta.xml
<CustomField>
    <fullName>PO_End_Date__c</fullName>
    <label>PO End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/PO_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>PO_Start_Date__c</fullName>
    <label>PO Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/PO_Status__c.field-meta.xml
<CustomField>
    <fullName>PO_Status__c</fullName>
    <label>PO Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Ship_to_Address__c.field-meta.xml
<CustomField>
    <fullName>Ship_to_Address__c</fullName>
    <label>Ship to Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Tax_Included__c.field-meta.xml
<CustomField>
    <fullName>Tax_Included__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax Included</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Half-Yearly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>ADHOC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer/Vendor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects12</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Customer_Project__c.field-meta.xml
<CustomField>
    <fullName>Customer_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Vendor Projects</relationshipLabel>
    <relationshipName>Customer_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>End Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (End Customer)</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <label>Payment Terms</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NET10</fullName>
            </value>
            <value>
                <fullName>NET30</fullName>
            </value>
            <value>
                <fullName>NET45</fullName>
            </value>
            <value>
                <fullName>NET60</fullName>
            </value>
            <value>
                <fullName>NET90</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_End_Date__c</fullName>
    <label>Project End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/TIG_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>TIG_Entity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TIG Entity Name</label>
    <referenceTo>TIG_Entity__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Project__c/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/Project_Team__c/Project_Team__c.object-meta.xml
<CustomObject>
    <description>This is child to Project where users can select a User and can assign a Role as well</description>
    <label>Project Team</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Project Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Lookup to Project to select Project</description>
    <inlineHelpText>Select Project Name Here</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project_Team__c/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/TIG_Entity__c/TIG_Entity__c.object-meta.xml
<CustomObject>
    <label>TIG Entity</label>
    <nameField>
        <label>TIG Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TIG Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TIG_Entity__c/fields/Country1__c.field-meta.xml
<CustomField>
    <fullName>Country1__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TIG_Entity__c/fields/Email_Address_for_Remittance__c.field-meta.xml
<CustomField>
    <fullName>Email_Address_for_Remittance__c</fullName>
    <label>Email Address for Remittance</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/TIG_Entity__c/fields/Email_for_Contact__c.field-meta.xml
<CustomField>
    <fullName>Email_for_Contact__c</fullName>
    <label>Email for Contact</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/TIG_Entity__c/fields/State1__c.field-meta.xml
<CustomField>
    <fullName>State1__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country1__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TIG_Entity__c/fields/Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code__c</fullName>
    <label>Tax Code</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TIG_Entity__c/fields/Tax_Name__c.field-meta.xml
<CustomField>
    <fullName>Tax_Name__c</fullName>
    <label>Tax Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TIG_Entity__c/fields/TIG_Entity_Code__c.field-meta.xml
<CustomField>
    <fullName>TIG_Entity_Code__c</fullName>
    <description>will hold TIG 3 digits code</description>
    <label>TIG Entity Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TIG_Entity__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip / Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei Darussalam</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>United Arab Emirates</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Australian Capital Territory</fullName>
    </customValue>
    <customValue>
        <fullName>New South Wales</fullName>
    </customValue>
    <customValue>
        <fullName>Northern Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Queensland</fullName>
    </customValue>
    <customValue>
        <fullName>South Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Tasmania</fullName>
    </customValue>
    <customValue>
        <fullName>Victoria</fullName>
    </customValue>
    <customValue>
        <fullName>Western Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina Faso</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Burundi</fullName>
    </customValue>
    <customValue>
        <fullName>Haryana</fullName>
    </customValue>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Project_Trigger_Handler_Test.cls
@isTest
public class Project_Trigger_Handler_Test {
    
    @TestSetup
    public static void testDataCreation()
    {
    //    List<Project__c> projectList = new List<Project__c>();
        Account acc= Test_Data_Factory.createAccount('Customer');
        insert acc;
        Contact con=Test_Data_Factory.createContact();
        insert con;
        
        Project__c projOneTime=Test_Data_Factory.createProject('One Time','Customer');
        projOneTime.Customer__c=acc.id;
        projOneTime.End_Customer__c=acc.id;
        projOneTime.Billing_Frequency__c='One Time';
        insert projOneTime;
        
        Project__c projWeekly=Test_Data_Factory.createProject('Weekly','Customer');
        projWeekly.Customer__c=acc.id;
        projWeekly.End_Customer__c=acc.id;
        projWeekly.Billing_Frequency__c='Weekly';
        insert projWeekly;
        
        Project__c projBiWeekly=Test_Data_Factory.createProject('Bi-Weekly','Customer');
        projBiWeekly.Customer__c=acc.id;
        projBiWeekly.End_Customer__c=acc.id;
        projBiWeekly.Billing_Frequency__c='Bi-Weekly';
        insert projBiWeekly;
        
        Project__c projMonthly=Test_Data_Factory.createProject('Monthly','Customer');
        projMonthly.Customer__c=acc.id;
        projMonthly.End_Customer__c=acc.id;
        projMonthly.Billing_Frequency__c='Monthly';
        insert projMonthly; 
        
        Project__c projQuarterly=Test_Data_Factory.createProject('Quarterly','Customer');
        projQuarterly.Customer__c=acc.id;
        projQuarterly.End_Customer__c=acc.id;
        projQuarterly.Billing_Frequency__c='Quarterly';
        insert projQuarterly; 
        
        Project__c projHalfYearly=Test_Data_Factory.createProject('Half-Yearly','Customer');
        projHalfYearly.Customer__c=acc.id;
        projHalfYearly.End_Customer__c=acc.id;
        projHalfYearly.Billing_Frequency__c='Half-Yearly';
        insert projHalfYearly;
        
        Project__c projYearly=Test_Data_Factory.createProject('Yearly','Customer');
        projYearly.Customer__c=acc.id;
        projYearly.End_Customer__c=acc.id;
        projYearly.Billing_Frequency__c='Yearly';
        insert projYearly;
        
        Project_Team__c pt=Test_Data_Factory.createProjectTeam('Internal', False);
        pt.Project__c=projOneTime.Id;
        insert pt;
    //done by Sahil Madan
     /*   Account CustomerAcc = Test_Data_Factory.createAccount('Customer');
        CustomerAcc.BillingStreet = 'Old';
        CustomerAcc.BillingCity = 'Kaithal';
        CustomerAcc.BillingState = 'Haryana';
        CustomerAcc.BillingPostalCode = '136027';
        CustomerAcc.BillingCountry = 'India';
        CustomerAcc.ShippingStreet = 'Test';
        CustomerAcc.ShippingCity = 'Siwan';
        CustomerAcc.ShippingState = 'Haryana';
        CustomerAcc.ShippingPostalCode = '136027';
        CustomerAcc.ShippingCountry = 'India';
        insert CustomerAcc;
        
		Account VendorAcc = Test_Data_Factory.createAccount('Vendor');
        VendorAcc.Name='TaTa';
        VendorAcc.Type='Partner';
        VendorAcc.Type_of_Partner__c = 'Indirect';
        VendorAcc.BillingStreet = 'Old';
        VendorAcc.BillingCity = 'Kaithal';
        VendorAcc.BillingState = 'Haryana';
        VendorAcc.BillingPostalCode = '136027';
        VendorAcc.BillingCountry = 'India';
        VendorAcc.ShippingStreet = 'Test';
        VendorAcc.ShippingCity = 'Siwan';
        VendorAcc.ShippingState = 'Haryana';
        VendorAcc.ShippingPostalCode = '136027';
        VendorAcc.ShippingCountry = 'India';
        insert VendorAcc;
        
        TIG_Entity__c tigEntity1 = Test_Data_Factory.createTIGEntity();
        tigEntity1.Name='TIG Kaithal';
        tigEntity1.TIG_Entity_Code__c='KTL';
        tigEntity1.Tax_Name__c = 'test';
        tigEntity1.Tax_Code__c = '908';
        tigEntity1.Street_Address__c = 'Kaithal';
        tigEntity1.City__c = 'Kaithal';
        tigEntity1.Zip_Postal_Code__c = '136027';
        tigEntity1.State1__c = 'Haryana';
        tigEntity1.Country1__c = 'India';
        tigEntity1.Email_Address_for_Remittance__c='ktl@gmail.com';
        tigEntity1.Email_for_Contact__c='ktl@gmail.com';
        tigEntity1.OwnerId = UserInfo.getUserId();
        insert tigEntity1;
        
        Project__c CusProject = Test_Data_Factory.createProject('Monthly', 'Customer');
        CusProject.Name = 'KaithalCustomerProject';
        CusProject.Project_Start_Date__c = Date.today();
        CusProject.Project_End_Date__c = Date.today().addDays(5);
        CusProject.Customer__c = CustomerAcc.id;
        CusProject.End_Customer__c = CustomerAcc.id;
        CusProject.TIG_Entity_Name__c = tigEntity1.id;
        CusProject.Payment_Term__c = 'NET30';
        CusProject.Billing_Frequency__c ='Monthly';
        insert CusProject;
        
        Order__c SalesOrder = Test_Data_Factory.createOrder('Sales Order');
        SalesOrder.Name = 'KaithalSalesOrder';
        SalesOrder.PO_Status__c = 'Draft';
        SalesOrder.Customer__c = CustomerAcc.id;
        SalesOrder.Project__c = CusProject.id;
        SalesOrder.PO_Start_Date__c = Date.today();
        SalesOrder.PO_End_Date__c = Date.today().addDays(5);
        SalesOrder.PO_Amount__c = 1100;
        SalesOrder.Tax_Included__c = 'Yes';
        SalesOrder.Bill_to_Address__c = 'Test';
        SalesOrder.Ship_to_Address__c = 'Test';
        insert SalesOrder;
        
               
		Project__c proj1 = Test_Data_Factory.createProject('Monthly', 'Vendor');
        proj1.Name = 'KaithalVendorProject';
        proj1.Project_Start_Date__c = Date.today();
        proj1.Project_End_Date__c = Date.today().addDays(5);
        proj1.Customer__c = VendorAcc.id;
        proj1.Customer_Project__c = CusProject.Id;
        proj1.TIG_Entity_Name__c = tigEntity1.id;
        proj1.Payment_Term__c = 'NET30';
        proj1.Billing_Frequency__c ='Monthly'; 
        insert proj1;
        
        Order__c ord1 = Test_Data_Factory.createOrder('Purchase Order');
        ord1.name = 'KaithalPO1';
        ord1.PO_Status__c = 'Draft';
        ord1.Customer__c = VendorAcc.id;
        ord1.Customer_Purchase_Order__c = SalesOrder.id;
        ord1.Project__c = proj1.id;
        ord1.PO_Start_Date__c = Date.today();
        ord1.PO_End_Date__c = Date.today().addDays(5);
        ord1.PO_Amount__c = 1000;
        ord1.Tax_Included__c = 'Yes';
        ord1.Delivery_Instructions__c = 'Test';
        ord1.Ship_to_Address__c = 'Test';
        projectList.add(proj1);
        
       	Order__c ord2 = Test_Data_Factory.createOrder('Purchase Order');
        ord2.name = 'KaithalPO2';
        ord2.PO_Status__c = 'Draft';
        ord2.Customer__c = VendorAcc.id;
        ord2.Customer_Purchase_Order__c = SalesOrder.id;
        ord2.Project__c = proj1.id;
        ord2.PO_Start_Date__c = Date.today();
        ord2.PO_End_Date__c = Date.today().addDays(5);
        ord2.PO_Amount__c = 1000;
        ord2.Tax_Included__c = 'Yes';
        ord2.Delivery_Instructions__c = 'Test';
        ord2.Ship_to_Address__c = 'Test';
        projectList.add(proj1);
        
projectList = [Select id, name from project__c where Customer_Project__c != null];
        system.debug('############'+projectList.size());
        ProjectTriggerHandler.UpdateTotalSumOfVendorProjects(projectList);
        */
    }
    
    public static TestMethod void testProjectTriggerHandler()
    {
        ProjectTriggerHandler.createAutomatedBillingInfo([SELECT Name,Project_Start_Date__c,Project_End_Date__c,Payment_Term__c,Billing_Frequency__c,Project__c.RecordTypeId from Project__c]);
    }
    
}