force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer/Vendor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sales Invoice</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Purchase Invoice</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Customer_Project__c.field-meta.xml
<CustomField>
    <fullName>Customer_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Vendor Invoices</relationshipLabel>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Customer__c</field>
            <operation>equals</operation>
            <valueField>Project__c.Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/TIG_Entity__c.field-meta.xml
<CustomField>
    <fullName>TIG_Entity__c</fullName>
    <formula>TEXT(Project__r.Total_IT_Billing_Entity__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TIG Entity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Custom Order Object</description>
    <label>TIG Order</label>
    <nameField>
        <label>PO Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <formula>TEXT(Project__r.Billing_Frequency__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing Frequency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer/Vendor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4 AND 6) OR (3 AND 5 AND 6)</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sales Order</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Purchase Order</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Indirect Purchase Order</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Sales_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Customer_Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Purchase Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sales Order</value>
        </filterItems>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>startsWith</operation>
            <valueField>Order__c.Customer_Purchase_Order__r.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Vendor Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Time</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Half-Yearly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>ADHOC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer/Vendor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects12</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Customer_Project__c.field-meta.xml
<CustomField>
    <fullName>Customer_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Vendor Projects</relationshipLabel>
    <relationshipName>Customer_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>End Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (End Customer)</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/TIG_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>TIG_Entity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TIG Entity Name</label>
    <referenceTo>TIG_Entity__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Project__c/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/Project_Services__c/Project_Services__c.object-meta.xml
<CustomObject>
    <label>Project Services</label>
    <nameField>
        <label>Project Services Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Services__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Projects Services</relationshipLabel>
    <relationshipName>Projects_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Services__c/recordTypes/FTE.recordType-meta.xml
<RecordType>
    <fullName>FTE</fullName>
    <active>true</active>
    <label>FTE</label>
</RecordType>

force-app/main/default/objects/Project_Sites__c/Project_Sites__c.object-meta.xml
<CustomObject>
    <label>Project Sites</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Sites__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Projects Sites</relationshipLabel>
    <relationshipName>Projects_Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Team__c/Project_Team__c.object-meta.xml
<CustomObject>
    <description>This is child to Project where users can select a User and can assign a Role as well</description>
    <label>Project Team</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Project Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Lookup to Project to select Project</description>
    <inlineHelpText>Select Project Name Here</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project_Team__c/recordTypes/External.recordType-meta.xml
<RecordType>
    <fullName>External</fullName>
    <active>true</active>
    <label>External</label>
</RecordType>

force-app/main/default/objects/Project_Team__c/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/classes/InvoiceHandler_Test.cls
@isTest
public class InvoiceHandler_Test {
    
    @TestSetup
    public static void testDataCreation()
    {
        Account Customer= Test_Data_Factory.createAccount('Customer');
        insert Customer;
        
        Account vendor= Test_Data_Factory.createAccount('Vendor');
        insert vendor;
        
        Contact con=Test_Data_Factory.createContact();
        insert con;
        
        TIG_Entity__c tigEntity=Test_Data_Factory.createTIGEntity();
        insert tigEntity;
        
        Project__c projOneTimeCustomer=Test_Data_Factory.createProject('One Time','Customer');
        projOneTimeCustomer.Customer__c=Customer.id;
        projOneTimeCustomer.End_Customer__c=Customer.id;
        projOneTimeCustomer.TIG_Entity_Name__c=tigEntity.id;
        insert projOneTimeCustomer;
        
        Project__c projOneTimeVendor=Test_Data_Factory.createProject('One Time','Vendor');
        projOneTimeVendor.Customer__c=Vendor.id;
        projOneTimeVendor.End_Customer__c=Customer.id;
        projOneTimeVendor.Customer_Project__c=projOneTimeCustomer.id;
        projOneTimeVendor.TIG_Entity_Name__c=tigEntity.id;
        insert projOneTimeVendor;
        
        Project__c Weekly=Test_Data_Factory.createProject('Weekly','Customer');
        Weekly.Customer__c=Customer.id;
        Weekly.End_Customer__c=Customer.id;
        Weekly.Billing_Frequency__c='Weekly';
        insert Weekly;        
        System.debug('projId :'+Weekly.id);
        
        List<Project_Team__c> teamList=new List<Project_Team__c>();
        Project_Team__c pt=Test_Data_Factory.createProjectTeam('Internal', False);
        pt.Project__c=projOneTimeCustomer.Id;
        insert pt;
        
        Project_Team__c pt1=Test_Data_Factory.createProjectTeam('Internal', true);
        pt1.Project__c=projOneTimeCustomer.Id;
        insert pt1;
        
        Project_Team__c pt2=Test_Data_Factory.createProjectTeam('External', true);
        pt2.Project__c=projOneTimeCustomer.Id;
        insert pt2;
        
        Order__c salesOrder=Test_Data_Factory.createOrder('Sales Order');
        salesOrder.Customer__c=Customer.id;
        salesOrder.Project__c=projOneTimeCustomer.id;
        insert salesOrder;
        
        Order__c purchaseOrder=Test_Data_Factory.createOrder('Purchase Order');
        purchaseOrder.Customer__c=Vendor.id;
        purchaseOrder.Project__c=projOneTimeVendor.id;
        purchaseOrder.Customer_Purchase_Order__c=salesOrder.Id;
        insert purchaseOrder;   
        
        Project_Sites__c site=Test_Data_Factory.createSite();
        site.Project__c=projOneTimeCustomer.id;
        insert site;
        
        Project_Services__c service=Test_Data_Factory.createService('FTE');
        service.Project__c=projOneTimeCustomer.id;
        service.Project_Site__c=site.id;
        service.Vendor__c=vendor.id;
        service.Vendor_Purchase_Order__c=purchaseOrder.id;
        service.Purchase_Order__c=salesOrder.id;
        service.Vendor_Project__c=projOneTimeVendor.id;
        insert service;
        
        Invoice__c salesInvoice=Test_Data_Factory.createInvoice('Sales Invoice');
        salesInvoice.Customer__c=Customer.id;
        salesInvoice.Project__c=projOneTimeCustomer.id;
        salesInvoice.Purchase_Order__c=salesOrder.id;
        insert salesInvoice;
        
        Invoice__c purchaseInvoice=Test_Data_Factory.createInvoice('Purchase Invoice');
        purchaseInvoice.Customer__c=Vendor.id;
        purchaseInvoice.Project__c=projOneTimeVendor.id;
        purchaseInvoice.Purchase_Order__c=purchaseOrder.id;
        purchaseInvoice.Customer_Project__c=projOneTimeCustomer.id;
        insert purchaseInvoice;
        
        Invoice__c purchaseInvoice2=Test_Data_Factory.createInvoice('Purchase Invoice');
        purchaseInvoice2.Customer__c=Vendor.id;
        purchaseInvoice2.Project__c=projOneTimeVendor.id;
        purchaseInvoice2.Purchase_Order__c=purchaseOrder.id;
        purchaseInvoice2.Customer_Project__c=projOneTimeCustomer.id;
        insert purchaseInvoice2;
        
        Invoice__c inv1=Test_Data_Factory.createInvoice('Sales Invoice');
        inv1.Customer__c=Customer.id;
        inv1.Project__c=projOneTimeCustomer.id;
        inv1.Purchase_Order__c=salesOrder.id;
        insert inv1;  
        
        
        Invoice_Line_Item__c ilt=Test_Data_Factory.createInvoiceLineItem();
        ilt.Invoice__c=purchaseInvoice.id;
        insert ilt;
    }
    
    
    public static TestMethod void testMethodGenerateInvoiceNumber()
    {
        
        Order__c po=[select id,PO_Status__c from Order__c  where RecordType.Name='Purchase Order' limit 1];
        po.PO_Status__c='Released';
        update po;
        try{
            Invoice__c inv=[select id,status__c from Invoice__c  where RecordType.Name='Purchase Invoice' limit 1];
            inv.Disputed_Amount__c=5;
            inv.Status__c='Disputed';
            inv.Stage__c='On Hold';
            update inv;
            inv.Disputed_Amount__c=null;
            update inv;
        }Catch(Exception ex)
        {
            System.Assert(ex.getMessage().contains(System.Label.Dispute_Amount_Error));
            
        }
        
        
        //If no of invoice line item is zero
        try{
            Invoice__c inv=[select id,status__c from Invoice__c  where RecordType.Name='Purchase Invoice' AND Number_of_Invoice_Line_Items__c=0 limit 1  ];
            inv.Status__c='Validate Invoice';
            inv.Stage__c='Submitted';
            update inv;
        }Catch(Exception ex)
        {
            System.Assert(ex.getMessage().contains('Please add line items to the invoice before proceeding.'));
            
        }
        
        try{
            Invoice__c inv=[select id,status__c from Invoice__c  where RecordType.Name='Purchase Invoice' AND Number_of_Invoice_Line_Items__c=0 limit 1  ];
            inv.Status__c='Validate Invoice';
           // update inv;
        }Catch(Exception ex)
        {
            // System.Assert(ex.getMessage());
            
        }
        
        Invoice__c inv1=[select id,status__c from Invoice__c  where RecordType.Name='Purchase Invoice' limit 1];
        inv1.Status__c='Validate Invoice';
        //update inv1;
    }  
    
}