force-app/main/default/objects/Vendor_Partner_Presence__c/Vendor_Partner_Presence__c.object-meta.xml
<CustomObject>
    <label>Vendor Partner Presence</label>
    <nameField>
        <displayFormat>VPP{0000}</displayFormat>
        <label>Vendor Partner Presence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Partner Presences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Partner_Presence__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor Partner Presences</relationshipLabel>
    <relationshipName>Vendor_Partner_Presences</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_Partner_Presence__c/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>false</active>
    <label>Partner</label>
</RecordType>

force-app/main/default/classes/VendorPartnerController.cls
public with sharing class VendorPartnerController {
    @AuraEnabled
    public static void savePartner(List<Vendor_Partner_Presence__c> partnerList,String accId){
        try {
            if (!partnerList.isEmpty()) {
                List<Vendor_Partner_Presence__c> newPartnewList= new List<Vendor_Partner_Presence__c>();
                for(Vendor_Partner_Presence__c partner:partnerList){
                    partner.Company__c=accId;
                    newPartnewList.add(partner);
                }
                if(!newPartnewList.isEmpty()){
                    Insert newPartnewList;  
                }  
                System.debug('newPartnewList'+newPartnewList);
            }
           
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static List < Map < String, String >> getPickListValues(String objApiName, String fieldName) {
        List < Map < String, String >> options = new List < Map < String, String >> ();
        Map < String, Schema.SObjectType > objGlobalMap = Schema.getGlobalDescribe();
        Schema.SObjectType objType = Schema.getGlobalDescribe().get(objApiName);
        if (objType == null) {
            return options;
        }
        Schema.DescribeSObjectResult sobjectDescribe = objType.getDescribe();
        Map < String, Schema.SObjectField > fieldMap = sobjectDescribe.fields.getMap();
        if (fieldMap.get(fieldName) == null) {
            return options;
        }
        List < Schema.PicklistEntry > pickListValues = fieldMap.get(fieldName).getDescribe().getPickListValues();
        for (Schema.PicklistEntry f: pickListValues) {
            Map < String, String > values = new Map < String, String > {
                'label' => f.getLabel(),
                'value' => f.getValue()
            };
            options.add(values);
        }
        return options;
    }
}